// ── MediAssist PDF Export Service ──
// Generates professional prescription & health report PDFs using jsPDF

import jsPDF from 'jspdf';

const MINT   = [0, 212, 168];
const DARK   = [8, 14, 28];
const BLUE   = [74, 159, 213];
const GRAY   = [136, 153, 187];
const LGRAY  = [240, 244, 255];
const WHITE  = [255, 255, 255];
const CORAL  = [255, 107, 107];
const AMBER  = [255, 170, 68];

function hex(rgb) { return `#${rgb.map(v => v.toString(16).padStart(2,'0')).join('')}`; }

// ── Header banner ──
function drawHeader(doc, title, subtitle) {
  // Dark banner
  doc.setFillColor(...DARK);
  doc.rect(0, 0, 210, 36, 'F');

  // Mint accent bar
  doc.setFillColor(...MINT);
  doc.rect(0, 0, 4, 36, 'F');

  // Logo circle
  doc.setFillColor(...MINT);
  doc.circle(22, 18, 9, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('+', 22, 22, { align: 'center' });

  // App name
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('MediAssist Pro', 36, 16);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text('AI-Powered Health Companion', 36, 23);

  // Title right side
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...MINT);
  doc.text(title, 210 - 14, 16, { align: 'right' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(subtitle, 210 - 14, 23, { align: 'right' });

  return 44; // y after header
}

// ── Section heading ──
function sectionHead(doc, y, text, color = MINT) {
  doc.setFillColor(...color.map(v => Math.round(v * 0.15)));
  doc.roundedRect(14, y, 182, 8, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...color);
  doc.text(text.toUpperCase(), 18, y + 5.5);
  return y + 13;
}

// ── Info row ──
function infoRow(doc, y, label, value, labelColor = GRAY, valueColor = DARK, bold = false) {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...labelColor);
  doc.text(label, 18, y);
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setTextColor(...valueColor);
  doc.text(String(value || '—'), 75, y);
  return y + 6;
}

// ── Two-column row ──
function twoCol(doc, y, l1, v1, l2, v2) {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(l1, 18, y);
  doc.setTextColor(...DARK);
  doc.text(String(v1 || '—'), 65, y);
  doc.setTextColor(...GRAY);
  doc.text(l2, 114, y);
  doc.setTextColor(...DARK);
  doc.text(String(v2 || '—'), 161, y);
  return y + 6;
}

// ── Divider ──
function divider(doc, y, color = [220, 228, 248]) {
  doc.setDrawColor(...color);
  doc.setLineWidth(0.3);
  doc.line(14, y, 196, y);
  return y + 4;
}

// ── Footer ──
function drawFooter(doc, pageNum) {
  const h = doc.internal.pageSize.height;
  doc.setFillColor(...LGRAY);
  doc.rect(0, h - 16, 210, 16, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text('⚕ Generated by MediAssist Pro · For medical reference only · Always consult a licensed physician', 14, h - 8);
  doc.text(`Page ${pageNum}`, 196, h - 8, { align: 'right' });
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, 105, h - 8, { align: 'center' });
}

// ══════════════════════════════════════════════
// EXPORT 1 — Single Prescription PDF
// ══════════════════════════════════════════════
export function exportPrescriptionPDF(prescription, patient, user) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = drawHeader(doc, 'PRESCRIPTION', `Rx #${prescription._id?.slice(-6)?.toUpperCase() || 'XXXXXX'}`);

  // ── Patient info ──
  y = sectionHead(doc, y, '👤 Patient Information');
  y = twoCol(doc, y, 'Patient Name', user?.name || patient?.name || '—', 'Patient ID', patient?.patientId || '—');
  y = twoCol(doc, y, 'Age / Gender', `${patient?.age || '?'} yrs / ${patient?.gender || '—'}`, 'Blood Group', patient?.bloodGroup || '—');
  y = twoCol(doc, y, 'Phone', patient?.phone || '—', 'City', patient?.city || 'Asansol, WB');
  if (patient?.allergies?.length) {
    y = infoRow(doc, y, '⚠ Allergies', patient.allergies.join(', '), [...CORAL], CORAL, true);
  }
  y = divider(doc, y + 2);

  // ── Rx details ──
  y = sectionHead(doc, y, '💊 Prescription Details', BLUE);

  // Big medicine name box
  doc.setFillColor(...LGRAY);
  doc.roundedRect(14, y, 182, 22, 3, 3, 'F');
  doc.setFillColor(...MINT);
  doc.roundedRect(14, y, 4, 22, 2, 2, 'F');

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text(prescription.medicineName || '—', 22, y + 9);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(prescription.purpose || 'As prescribed', 22, y + 16);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...MINT);
  doc.text(prescription.dosage || '—', 190, y + 9, { align: 'right' });

  y += 27;

  y = twoCol(doc, y, 'Frequency',   prescription.frequency || '—', 'Timing',      prescription.timing || '—');
  y = twoCol(doc, y, 'Duration',    prescription.duration || '—',  'Days Supply', `${prescription.daysSupply || '—'} days`);
  y = twoCol(doc, y, 'Cost/Unit',   prescription.costPerUnit || '—', 'Refills Left', String(prescription.refillsLeft ?? '—'));
  y = twoCol(doc, y, 'Pharmacy',    prescription.pharmacy || '—', 'Status', (prescription.status || 'active').replace('_',' ').toUpperCase());
  y = divider(doc, y + 2);

  // ── Doctor info ──
  y = sectionHead(doc, y, '👨‍⚕️ Prescribing Physician', MINT);
  y = twoCol(doc, y, 'Doctor',      prescription.prescribedBy || '—', 'Date', prescription.prescribedAt || new Date().toLocaleDateString('en-IN'));
  y = divider(doc, y + 2);

  // ── Instructions ──
  if (prescription.notes) {
    y = sectionHead(doc, y, '📋 Instructions & Notes', AMBER);
    doc.setFillColor(255, 248, 230);
    doc.roundedRect(14, y, 182, 14, 2, 2, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(prescription.notes, 170);
    doc.text(lines, 18, y + 5);
    y += 19;
  }

  // ── Dosage schedule visual ──
  y = sectionHead(doc, y, '⏰ Daily Schedule', MINT);
  const schedule = buildSchedule(prescription);
  const colW = 182 / schedule.length;
  schedule.forEach((slot, i) => {
    const x = 14 + i * colW;
    const active = slot.active;
    doc.setFillColor(...(active ? MINT.map(v => Math.round(v * 0.15)) : [245, 247, 255]));
    doc.roundedRect(x + 1, y, colW - 2, 18, 2, 2, 'F');
    if (active) {
      doc.setFillColor(...MINT);
      doc.circle(x + colW / 2, y + 7, 3, 'F');
    }
    doc.setFontSize(7);
    doc.setFont('helvetica', active ? 'bold' : 'normal');
    doc.setTextColor(...(active ? MINT : GRAY));
    doc.text(slot.time, x + colW / 2, y + 14, { align: 'center' });
  });
  y += 23;

  // ── Warning box ──
  doc.setFillColor(255, 242, 242);
  doc.roundedRect(14, y, 182, 12, 2, 2, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...CORAL);
  doc.text('⚠  IMPORTANT:', 18, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 40, 40);
  doc.text('This prescription is for the named patient only. Do not share medication. Keep out of reach of children.', 50, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text('Always take as directed by your physician. Report any adverse reactions immediately.', 18, y + 10);

  drawFooter(doc, 1);
  doc.save(`Prescription_${(prescription.medicineName || 'medicine').replace(/\s+/g,'-')}_${Date.now()}.pdf`);
}

// ══════════════════════════════════════════════
// EXPORT 2 — Full Health Report PDF
// ══════════════════════════════════════════════
export function exportHealthReportPDF(patient, user, prescriptions = [], vitals = {}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = drawHeader(doc, 'HEALTH REPORT', new Date().toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' }));

  // ── Patient summary card ──
  doc.setFillColor(...LGRAY);
  doc.roundedRect(14, y, 182, 34, 3, 3, 'F');

  // Avatar circle
  doc.setFillColor(...MINT);
  doc.circle(28, y + 17, 10, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text((user?.name || 'P').slice(0,1).toUpperCase(), 28, y + 21, { align: 'center' });

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text(user?.name || 'Patient', 42, y + 14);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(`ID: ${patient?.patientId || '—'} · ${patient?.gender || '—'} · ${patient?.age || '?'} yrs`, 42, y + 21);
  doc.text(`${patient?.city || 'Asansol'}, West Bengal · ${user?.email || ''}`, 42, y + 27);

  // BMI badge
  const bmi = patient?.bmi;
  const bmiColor = !bmi ? GRAY : bmi < 18.5 ? BLUE : bmi < 25 ? MINT : bmi < 30 ? AMBER : CORAL;
  doc.setFillColor(...bmiColor);
  doc.roundedRect(160, y + 8, 30, 18, 3, 3, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text(String(bmi || '—'), 175, y + 19, { align: 'center' });
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('BMI', 175, y + 24, { align: 'center' });

  y += 39;

  // ── Vitals summary ──
  y = sectionHead(doc, y, '💓 Current Vitals', CORAL);
  const vitalItems = [
    ['Heart Rate', `${vitals.heartRate || '74'} bpm`, CORAL],
    ['Blood Pressure', `${vitals.bp || '118/76'} mmHg`, BLUE],
    ['SpO2', `${vitals.spo2 || '99'}%`, MINT],
    ['Temperature', `${vitals.temp || '98.4'}°F`, AMBER],
  ];
  const vw = 182 / vitalItems.length;
  vitalItems.forEach(([lbl, val, col], i) => {
    const x = 14 + i * vw;
    doc.setFillColor(...col.map(v => Math.round(v * 0.12)));
    doc.roundedRect(x + 1, y, vw - 2, 20, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...col);
    doc.text(val, x + vw/2, y + 10, { align: 'center' });
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY);
    doc.text(lbl, x + vw/2, y + 16, { align: 'center' });
  });
  y += 25;

  // Physical stats
  y = twoCol(doc, y, 'Height', `${patient?.heightCm || '—'} cm`, 'Weight', `${patient?.weightKg || '—'} kg`);
  y = twoCol(doc, y, 'Waist', `${patient?.waistCm || '—'} cm`, 'Blood Group', patient?.bloodGroup || '—');
  y = divider(doc, y + 2);

  // ── Medical history ──
  y = sectionHead(doc, y, '🏥 Medical History', BLUE);
  y = infoRow(doc, y, 'Chronic Conditions', (patient?.chronicConditions || []).join(', ') || 'None reported');
  y = infoRow(doc, y, '⚠ Drug Allergies', (patient?.allergies || []).join(', ') || 'None', GRAY, CORAL, true);
  y = infoRow(doc, y, 'Past Surgeries', (patient?.pastSurgeries || []).join(', ') || 'None');
  y = infoRow(doc, y, 'Family History', (patient?.familyHistory || []).join(', ') || 'None reported');
  y = twoCol(doc, y, 'Smoking', patient?.smokingStatus || 'Non-Smoker', 'Alcohol', patient?.alcoholUse || 'None');
  y = divider(doc, y + 2);

  // ── Active medications ──
  y = sectionHead(doc, y, '💊 Active Medications', MINT);
  if (!prescriptions.length) {
    doc.setFontSize(8); doc.setTextColor(...GRAY);
    doc.text('No active prescriptions recorded.', 18, y); y += 8;
  } else {
    // Table header
    doc.setFillColor(...DARK);
    doc.rect(14, y, 182, 7, 'F');
    doc.setFontSize(7); doc.setFont('helvetica', 'bold'); doc.setTextColor(...MINT);
    ['Medicine', 'Dosage', 'Frequency', 'Prescribed By', 'Status'].forEach((h, i) => {
      doc.text(h, [18, 65, 100, 135, 175][i], y + 5);
    });
    y += 9;

    prescriptions.forEach((rx, idx) => {
      if (idx % 2 === 0) { doc.setFillColor(...LGRAY); doc.rect(14, y - 1, 182, 7, 'F'); }
      doc.setFontSize(7); doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK);
      doc.text((rx.medicineName || '').slice(0, 22), 18, y + 4);
      doc.text((rx.dosage || '').slice(0, 14), 65, y + 4);
      doc.text((rx.frequency || '').slice(0, 16), 100, y + 4);
      doc.text((rx.prescribedBy || '').slice(0, 18), 135, y + 4);
      const sc = rx.status || 'active';
      doc.setTextColor(...(sc === 'active' ? MINT : sc === 'refill_needed' ? AMBER : CORAL));
      doc.text(sc.replace('_',' '), 175, y + 4);
      y += 7;
    });
    y += 4;
  }

  drawFooter(doc, 1);
  doc.save(`HealthReport_${(user?.name || 'Patient').replace(/\s+/g,'-')}_${Date.now()}.pdf`);
}

// ── helpers ──
function buildSchedule(rx) {
  const slots = [
    { time: 'Morning\n6-8 AM',    active: false },
    { time: 'Breakfast\n8-9 AM',  active: false },
    { time: 'Afternoon\n1-2 PM',  active: false },
    { time: 'Evening\n5-6 PM',    active: false },
    { time: 'Dinner\n8-9 PM',     active: false },
    { time: 'Bedtime\n10 PM',     active: false },
  ];
  const freq = (rx.frequency || '').toLowerCase();
  const timing = (rx.timing || '').toLowerCase();
  if (freq.includes('once'))    { slots[timing.includes('dinner') || timing.includes('night') ? 4 : 0].active = true; }
  if (freq.includes('twice'))   { slots[1].active = true; slots[4].active = true; }
  if (freq.includes('thrice') || freq.includes('three')) { slots[1].active = true; slots[3].active = true; slots[4].active = true; }
  if (timing.includes('morning')) slots[0].active = true;
  if (timing.includes('breakfast')) slots[1].active = true;
  if (timing.includes('dinner'))  slots[4].active = true;
  if (timing.includes('bed'))     slots[5].active = true;
  return slots;
}